version: '2'

services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_USER: root
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - skynet
#      skynet:
#        ipv4_address: 172.22.0.5
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin   
  db:
    networks:
      - skynet
#      skynet:
#        ipv4_address: 172.22.0.6
    container_name: postgresql_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: "/var/lib/postgresql/data/pgdata"
      #POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  skynet:
    driver: bridge
#    name: skynet-db-network
#    ipam:
#      config:
#        - subnet: 172.22.0.0/24
volumes:
  db-data:
  pgadmin-data: